package com.tradebot.exception;

public enum ErrorCode {
    BINANCE_RATE_LIMIT,
    BINANCE_AUTH,
    BINANCE_NETWORK,
    OPENROUTER_AUTH,
    OPENROUTER_RATE_LIMIT,
    OPENROUTER_NETWORK,
    OPENROUTER_BAD_JSON,
    OPENROUTER_INTERNAL,
    DB_DOWN,
    SCANNER_DOWN,
    VALIDATION,
    SCAN_RUNNING,
    SAFE_MODE,
    NOT_FOUND,
    BAD_REQUEST,
    FORBIDDEN_PERMISSION,
    FORBIDDEN_NOT_LOCAL,
    INTERNAL,
    SSE_DISCONNECT,
    CONFLICT_OR_STATE_ERROR
}
